version: "3.4"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
  api:
    build:
      context: ../
      dockerfile: docker/api/Dockerfile
    ports:
      - 8999:8999
    depends_on:
      - mongo
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
