- name: Login to docker hub
  tags: ['app']
  docker_login:
    email: "afaitelson@paloaltonetworks.com"
    username: "pingpongpulse"
    password: "Pin9P0ngPu|se"

- name: start containers
  tags: ['app']
  docker_service:
    project_name: pingpongpulse
    definition:
      version: "2.3"
      services:
        nginx:
          image: pingpongpulse/nginx
          ports:
            - "80:80"
            - "443:443"
        api:
          image: pingpongpulse/api
          ports:
            - "8999:8999"
        mongo:
          image: mongo
          restart: always
          ports:
            - "27017:27017"
