- name: Login to docker hub
  docker_login:
    email: "{{ docker_hub_email }}"
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"
  tags: docker_hub_login

- name: Remove containers
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - pingpongpulse_api_1
    - pingpongpulse_nginx_1

- name: Remove images
  docker_image:
    state: absent
    name: "{{ item }}"
  with_items:
    - pingpongpulse/api
    - pingpongpulse/nginx

- name: Start containers
  docker_service:
    project_name: pingpongpulse
    build: yes
    recreate: always
    definition:
      version: "3.4"
      services:
        mongo:
          image: mongo
          restart: always
          ports:
            - "27017:27017"
        api:
          image: pingpongpulse/api
          ports:
            - "8999:8999"
          depends_on:
            - mongo
        nginx:
          image: pingpongpulse/nginx
          ports:
            - "80:80"
            - "443:443"
          depends_on:
            - api
