- name: Login to docker hub
  docker_login:
    email: "{{ docker_hub_email }}"
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"
  tags: docker_hub_login

- name: Start containers
  docker_service:
    project_name: pingpongpulse
    definition:
      version: "2.3"
      services:
        mongo:
          image: mongo
          restart: always
          ports:
            - "27017:27017"
        api:
          image: pingpongpulse/api
          ports:
            - "8999:8999"
        nginx:
          image: pingpongpulse/nginx
          ports:
            - "80:80"
            - "443:443"
